name: Image resolution check

on:
  workflow_dispatch:
  push:
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check-res:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check all images for minimum resolution
        run: |
          for img in $(find . -name "*.png"); do
            echo "Checking $img"
            WIDTH=$(identify -format '%w' "$img")
            HEIGHT=$(identify -format '%h' "$img")
            [[ $WIDTH -lt 512 ]] && echo "$img width is smaller than 512px" && ERRORS=true
            [[ $HEIGHT -lt 512 ]] && echo "$img height is smaller than 512px" && ERRORS=true
            [[ $WIDTH -eq $HEIGHT ]] || echo "$img is not square" && ERRORS=true
          done
          [[ -z ERRORS ]] && exit 1
